export const SITE = {
  name: "El Gran Castillo de Jagua",
  tagline: "Authentic Dominican cuisine in Brooklyn, NY.",
  phone: "718-622-8700",
  address: "355 Flatbush Ave, Brooklyn, NY 11238",
  hours: {
    weekdays: { label: "Monday – Saturday", time: "8AM - 10PM" },
    sunday:   { label: "Sunday",            time: "8AM - 9PM" },
  },
  mapsUrl: "https://maps.app.goo.gl/5dcAWcnLoyizeC5W6",
};

export const NAV = [
  { label: "Menu",    href: "/menu"    },
  { label: "Hours & Contact", href: "/contact" },
] as const;

export const BREAKFAST_MENU_SECTIONS = [
  {
    title: "Breakfast Specials",
    note: "Served from 8am to 3pm every day. Substitute French Fries or Grits for Home Fries at no additional cost. Beef / Turkey Sausage and Turkey Bacon available at additional cost.",
    items: [
      { name: "2 Eggs Scrambled or Fried", price: "$9 / $11", desc: "With white, wheat, or rye toast & home fries. With bacon, ham, or pork sausage: $11." },
      { name: "French Toast", price: "$9 / $11", desc: "Classic french toast. With bacon, ham, or pork sausage: $11." },
      { name: "Pancakes", price: "$9 / $11", desc: "Fluffy pancakes. With bacon, ham, pork sausage, or chocolate chips: $11." },
      { name: "Poached or Boiled Egg", price: "+$1.50", desc: "Add to any breakfast special." },
    ],
  },
  {
    title: "Dominican Breakfast",
    note: "",
    items: [
      { name: "Mangu or Cassava with Salami", price: "$9", desc: "Traditional mashed plantain or cassava served with salami." },
      { name: "Mangu or Cassava with Fried Cheese", price: "$10", desc: "Classic Dominican breakfast with fried cheese." },
      { name: "Mangu or Cassava — Full Plate", price: "$13", desc: "With fried cheese, salami, and 2 eggs." },
      { name: "Fried Cheese, Salami & Eggs on a Hero", price: "$11", desc: "Dominican breakfast served on a hero roll." },
    ],
  },
  {
    title: "Fresh Omelettes",
    note: "Omelettes served with white, wheat, or rye toast and home fries.",
    items: [
      { name: "Cheese Omelette", price: "$11", desc: "American, Swiss, or cheddar." },
      { name: "Western Omelette", price: "$12", desc: "Ham, onions, and green peppers." },
      { name: "Vegetable Omelette", price: "$10", desc: "Tomatoes, onion, and green peppers." },
      { name: "Spanish Omelette", price: "$12", desc: "Onions, green peppers, and chorizo." },
      { name: "Avocado Omelette", price: "$12", desc: "Fresh avocado." },
    ],
  },
  {
    title: "Breakfast Sandwiches",
    note: "Served on white, wheat, rye, roll, or bagel. Add $1 for croissant or hero. Add American, Swiss, or cheddar cheese: +$1.",
    items: [
      { name: "With 2 Eggs", price: "$5", desc: "" },
      { name: "With 2 Eggs & Pork Bacon or Sausage", price: "$6", desc: "" },
      { name: "With 2 Eggs & Turkey Bacon or Turkey Sausage", price: "$7", desc: "" },
      { name: "Western Omelette Sandwich", price: "$8", desc: "" },
    ],
  },
  {
    title: "Breakfast Sides",
    note: "",
    items: [
      { name: "Toast", price: "$2", desc: "White, wheat, or rye." },
      { name: "Home Fries", price: "$6", desc: "" },
      { name: "Bacon", price: "$4.50", desc: "" },
      { name: "Sausage", price: "$4.50", desc: "" },
      { name: "Beef Sausage", price: "$3.75", desc: "" },
      { name: "Turkey Sausage", price: "$4.50", desc: "" },
      { name: "Fried Cheese", price: "$5.50", desc: "" },
      { name: "Bagel with Cream Cheese", price: "$3.50", desc: "" },
      { name: "Croissant", price: "$2.75", desc: "" },
      { name: "Corn Muffins", price: "$2.75", desc: "" },
      { name: "Corn Bread", price: "$3", desc: "" },
      { name: "Grits", price: "$3", desc: "" },
    ],
  },
] as const;

export const LUNCH_DINNER_MENU_SECTIONS = [
  {
    title: "Meat Selections",
    note: "Meat selections served with your choice of: Rice & Beans, Plantain & Salad, French Fries & Salad, Mashed Potato & Salad, Cassava & Salad, or Rice and Pigeon Peas.",
    items: [
      { name: "BBQ Chicken", price: "¼ $16 / ½ $19", desc: "" },
      { name: "½ Rotisserie Chicken", price: "$16", desc: "" },
      { name: "Fried Pork Meat Chunks", price: "$18", desc: "" },
      { name: "Fried Beef Chunks", price: "$24", desc: "" },
      { name: "Fried Chicken Chunks", price: "$16", desc: "" },
      { name: "Boneless Chicken Chunks", price: "$18", desc: "" },
      { name: "Roast Pork", price: "$17", desc: "" },
      { name: "Beef Stew", price: "$18", desc: "" },
      { name: "BBQ Spare Ribs", price: "$17", desc: "" },
      { name: "Broiled Chicken", price: "¼ $15 / ½ $18", desc: "" },
      { name: "Fried Chicken", price: "¼ $15 / ½ $18", desc: "" },
      { name: "Beef Steak in Sauce", price: "$22", desc: "" },
      { name: "Chicken Pepper Steak — Spanish Style", price: "$18", desc: "" },
      { name: "Beef Pepper Steak — Spanish Style", price: "$22", desc: "" },
      { name: "Steak with Onions", price: "$22", desc: "" },
      { name: "Breaded Steak", price: "$22", desc: "" },
      { name: "Fried Pork Chops", price: "(1) $15 / (2) $18", desc: "" },
      { name: "Chicken Steak", price: "$18", desc: "" },
      { name: "Breaded Pork Chops", price: "(1) $16 / (2) $19", desc: "" },
      { name: "Broiled Pork Chops", price: "(1) $17 / (2) $20", desc: "" },
      { name: "T-Bone Steak", price: "MP", desc: "Market price. Ask your server." },
      { name: "Stewed Oxtail", price: "$26", desc: "" },
    ],
  },
  {
    title: "Seafood",
    note: "Seafood served with your choice of side (same as meat selections).",
    items: [
      { name: "Fried or Sautéed Calamari", price: "$16", desc: "" },
      { name: "Grilled Fillet Fish", price: "$20", desc: "" },
      { name: "Fillet Fish in Tomato Sauce", price: "$20", desc: "" },
      { name: "Fried Fillet Fish", price: "$20", desc: "" },
      { name: "Tilapia Fillet", price: "$18", desc: "" },
      { name: "Red Salmon in Tomato Sauce", price: "$22", desc: "" },
      { name: "Broiled Red Salmon", price: "$22", desc: "" },
      { name: "Shrimp in Tomato Sauce", price: "$22", desc: "" },
      { name: "Grilled Shrimp", price: "$22", desc: "" },
      { name: "Fried Shrimp", price: "$22", desc: "" },
      { name: "Salmon Fillet", price: "$26", desc: "" },
      { name: "Red Snapper — Fried, Grilled, or in Tomato Sauce", price: "MP", desc: "" },
      { name: "Lobster in Tomato Sauce", price: "MP", desc: "" },
      { name: "Grilled Lobster", price: "MP", desc: "" },
    ],
  },
  {
    title: "Rice and Soupy Rice",
    note: "",
    items: [
      { name: "Chicken Soupy Rice", price: "$15", desc: "" },
      { name: "Rice with Squid", price: "$15", desc: "" },
      { name: "Rice with Sausage", price: "$15", desc: "" },
      { name: "Rice with Chicken", price: "$15", desc: "" },
      { name: "Rice with Shrimp", price: "$22", desc: "" },
      { name: "Shrimp Soupy Rice", price: "$22", desc: "" },
      { name: "Lobster Soupy Rice", price: "MP", desc: "" },
      { name: "Rice with Lobster", price: "MP", desc: "" },
      { name: "Pigeon Pea Soupy Rice", price: "$12", desc: "" },
      { name: "Calamari Soupy Rice", price: "$16", desc: "" },
      { name: "Chorizo Soupy Rice", price: "$16", desc: "" },
    ],
  },
  {
    title: "Mofongo",
    note: "Mashed green plantains. Add cheese to any mofongo: +$3.",
    items: [
      { name: "Plain Mofongo", price: "$11", desc: "" },
      { name: "Mofongo with Roast Pork", price: "$14", desc: "" },
      { name: "Mofongo with Cheese", price: "$15", desc: "" },
      { name: "Mofongo with Chicken", price: "$14", desc: "" },
      { name: "Camarofongo / Shrimp", price: "$22", desc: "" },
      { name: "Pork Chicharon", price: "$16", desc: "" },
    ],
  },
  {
    title: "Burgers",
    note: "Add bacon to any burger: +$2.",
    items: [
      { name: "Pure Beef Hamburger", price: "$6", desc: "" },
      { name: "Hamburger Deluxe", price: "$11", desc: "" },
      { name: "Cheeseburger", price: "$7", desc: "" },
      { name: "Cheeseburger Deluxe", price: "$12", desc: "" },
    ],
  },
  {
    title: "Mixed Seafood Combo with Yellow Rice Paella",
    note: "",
    items: [
      { name: "For 1", price: "MP", desc: "Market price." },
      { name: "For 2", price: "MP", desc: "Market price." },
    ],
  },
  {
    title: "Soups",
    note: "",
    items: [
      { name: "Chicken Soup", price: "$10", desc: "Every day." },
      { name: "Beef Soup", price: "$11", desc: "Monday, Wednesday, Saturday." },
      { name: "Sancocho — Beef & Chicken Spanish Soup", price: "$11", desc: "Tuesday, Thursday, Sunday." },
      { name: "Seafood Soup", price: "$14", desc: "Friday." },
    ],
  },
  {
    title: "Salads",
    note: "",
    items: [
      { name: "Lettuce, Tomato & Cucumber", price: "$6", desc: "" },
      { name: "Lettuce, Tomato & Avocado", price: "Ask", desc: "In season." },
      { name: "Chicken Salad", price: "$11", desc: "" },
      { name: "Grilled Chicken Salad", price: "$17", desc: "" },
      { name: "Shrimp Salad", price: "$22", desc: "" },
    ],
  },
] as const;